"""Project — the unit of registered consumption in CUPS.

A Project represents a single product a developer runs.
project_id is a UUID generated by CUPS on registration — not a Bot Token.
CUPS never knows the Bot Token. That's an operational secret.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from uuid import UUID


class ProductType(str, Enum):
    """Supported product types. Each has its own Entitlement catalog."""

    TITAN_FRAMEWORK = "titan-framework"
    BOT = "bot"
    MINI_APP = "mini-app"
    GAME = "game"


@dataclass
class Project:
    """A registered product instance owned by one Account.

    Registration is always explicit — no auto-discovery, no magic.
    The developer runs /addbot, CUPS returns project_id.
    """

    project_id: UUID          # unique identifier generated by CUPS
    owner_id: int             # account_id of the owner
    product: ProductType      # type of product
    name: str                 # human-chosen name
    registered_at: datetime = field(default_factory=datetime.utcnow)
    status: str = "active"    # active | suspended
